version: "3.3"
services:
  hrunmgr:
    # 这是jenkins发版打包的镜像，上传到私有仓库192.168.0.182
    image: 192.168.0.182:5000/hrunmgr:{tag}
    container_name: hrunmgr
    environment:
      - TZ=Asia/Shanghai
    #network_mode: host
    #只暴露2个端口
    ports:
      - "8080:8080"
      - "5555:5555"

    # 由于jenkins发版打包的镜像已经构建过代码，不用重复构建，因此去掉重复代码
    # build: .
    # volumes: # 映射目录， 方便读写
    #   - ./:/apps/HttpRunnerManager
    # #command: "/bin/sh", "-c", "while true; do sleep 100; done" # 让进程一直跑, 否则容器会exit
    # entrypoint: /apps/HttpRunnerManager/start.sh

