version: "3.3"
services:
  hrunmgr:
    build: .
    image: hrunmgr
    container_name: hrunmgr
    environment:
      - TZ=Asia/Shanghai
    #network_mode: host
    #只暴露2个端口
    ports:
      - "8080:8080"
      - "5555:5555"
    volumes: # 映射目录， 方便读写
      - ./:/apps/HttpRunnerManager
    #command: "/bin/sh", "-c", "while true; do sleep 100; done" # 让进程一直跑, 否则容器会exit
    entrypoint: /apps/HttpRunnerManager/start.sh

